// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:ringtalk/models/message/message.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chat_response.freezed.dart';
// optional: Since our chat_response class is serializable, we must add this line.
// But if chat_response was not serializable, we could skip it.
part 'chat_response.g.dart';

@freezed
class ChatResponse with _$ChatResponse {
  const factory ChatResponse({
    required bool ok,
    required String de,
    required String para,
    required List<Message> mensages,
  }) = _ChatResponse;

  factory ChatResponse.fromJson(Map<String, Object?> json) =>
      _$ChatResponseFromJson(json);
}
