// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'usuario.freezed.dart';
// optional: Since our Usuario class is serializable, we must add this line.
// But if Usuario was not serializable, we could skip it.
part 'usuario.g.dart';

@freezed
class Usuario with _$Usuario {
  const factory Usuario({
    required bool online,
    required String email,
    required String nombre,
    required String uid,
  }) = _Usuario;

  factory Usuario.fromJson(Map<String, Object?> json) =>
      _$UsuarioFromJson(json);
}
